### ISSUE TITLE
直接运行baichuan-13b-chat时候出现'type' object is not subscriptable

### ISSUE THREAD

**Issue by chenchch94** [FreedomIntelligence/CMB#6]
下载数据后尝试运行bash generate_fewshot.sh，出现以下问题：
Traceback (most recent call last):
  File "./src/generate_fewshot.py", line 6, in <module>
    from constants import id2worker_class
  File "/vepfs/chenchucheng/code/glm/CMB-main/src/constants.py", line 6, in <module>
    from workers.huatuo_chat import HuatuoChatWorker
  File "/vepfs/chenchucheng/code/glm/CMB-main/src/../workers/huatuo_chat.py", line 2, in <module>
    from .base import *
  File "/vepfs/chenchucheng/code/glm/CMB-main/src/../workers/base.py", line 20, in <module>
    class BaseWorker():
  File "/vepfs/chenchucheng/code/glm/CMB-main/src/../workers/base.py", line 239, in BaseWorker
    def generate_fewshot_examples(self, data: list[dict], use_cot=False):
TypeError: 'type' object is not subscriptable

直接在line6就出现报错，感觉是代码问题？是否有遇到过呢？

**Comment by chenchch94** [comment]
./CMB-main/src/../workers/base.py 的line293、line312也是同样的问题

**Comment by chenchch94** [comment]
在CMB-main文件下进入python环境后，直接运行from workers.base import *，就出现上面问题了。

**Comment by chenchch94** [comment]
需要python3.9及以上版本啊

**Comment by chenchch94** [comment]
需要什么样的运行环境呢？

**Comment by g-h-chen** [comment]
@chenchch94 Hii, thanks for your issue. 
- As pointed out by [this reddit post](https://www.reddit.com/r/learnpython/comments/xgi4m9/typeerror_type_object_is_not_subscriptable/), the type hints are only supported by Python 3.9+, so I suspect it's because you are using Python 3.8 or older versions. If you do not want to upgrade your Python, simply remove these hints should work. Namely, change ```def wrap(self, data: list[dict]):``` to ```def wrap(self, data):```. 
- I just checked the codes. They should be bugless to run. 

Good luck.

**Comment by g-h-chen** [comment]
> 需要什么样的运行环境呢？

@chenchch94 We've added some badges showing the versions of Python and major packages.

**Comment by chenchch94** [comment]
@g-h-chen thanks
